import { db } from '@/db';
import { careers } from '@/db/schema';

async function main() {
    const sampleCareers = [
        // Science Stream (8 careers)
        {
            career: 'Software Engineer',
            qualification: 'B.Tech/B.E. in Computer Science',
            stream: 'science',
            avgSalary: '₹6-15 LPA',
            salaryNumeric: 1050,
            jobType: 'IT',
            demand: 'High',
            growthRate: '22%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Doctor (MBBS)',
            qualification: 'MBBS + MD/MS',
            stream: 'science',
            avgSalary: '₹8-25 LPA',
            salaryNumeric: 1650,
            jobType: 'Medical',
            demand: 'High',
            growthRate: '18%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Data Scientist',
            qualification: 'B.Tech/M.Tech in CS/Statistics',
            stream: 'science',
            avgSalary: '₹8-20 LPA',
            salaryNumeric: 1400,
            jobType: 'IT',
            demand: 'High',
            growthRate: '25%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Pharmacist',
            qualification: 'B.Pharm/M.Pharm',
            stream: 'science',
            avgSalary: '₹3-7 LPA',
            salaryNumeric: 500,
            jobType: 'Medical',
            demand: 'Medium',
            growthRate: '12%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Research Scientist',
            qualification: 'M.Sc/Ph.D. in Science',
            stream: 'science',
            avgSalary: '₹5-12 LPA',
            salaryNumeric: 850,
            jobType: 'Research',
            demand: 'Medium',
            growthRate: '10%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Civil Engineer',
            qualification: 'B.Tech/B.E. in Civil Engineering',
            stream: 'science',
            avgSalary: '₹4-10 LPA',
            salaryNumeric: 700,
            jobType: 'Engineering',
            demand: 'Medium',
            growthRate: '14%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Biotechnology Specialist',
            qualification: 'B.Tech/M.Tech in Biotechnology',
            stream: 'science',
            avgSalary: '₹4-9 LPA',
            salaryNumeric: 650,
            jobType: 'Research',
            demand: 'Medium',
            growthRate: '16%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Mechanical Engineer',
            qualification: 'B.Tech/B.E. in Mechanical Engineering',
            stream: 'science',
            avgSalary: '₹4-11 LPA',
            salaryNumeric: 750,
            jobType: 'Engineering',
            demand: 'Medium',
            growthRate: '13%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Commerce Stream (6 careers)
        {
            career: 'Chartered Accountant',
            qualification: 'Graduation + CA',
            stream: 'commerce',
            avgSalary: '₹7-18 LPA',
            salaryNumeric: 1250,
            jobType: 'Finance',
            demand: 'High',
            growthRate: '17%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Financial Analyst',
            qualification: 'B.Com/BBA + MBA Finance',
            stream: 'commerce',
            avgSalary: '₹5-12 LPA',
            salaryNumeric: 850,
            jobType: 'Finance',
            demand: 'High',
            growthRate: '19%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Marketing Manager',
            qualification: 'BBA/B.Com + MBA Marketing',
            stream: 'commerce',
            avgSalary: '₹6-15 LPA',
            salaryNumeric: 1050,
            jobType: 'Marketing',
            demand: 'High',
            growthRate: '16%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Bank Manager',
            qualification: 'Graduation + Banking Exams',
            stream: 'commerce',
            avgSalary: '₹7-14 LPA',
            salaryNumeric: 1050,
            jobType: 'Finance',
            demand: 'Medium',
            growthRate: '12%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Investment Banker',
            qualification: 'B.Com/BBA + MBA Finance',
            stream: 'commerce',
            avgSalary: '₹8-22 LPA',
            salaryNumeric: 1500,
            jobType: 'Finance',
            demand: 'High',
            growthRate: '20%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Tax Consultant',
            qualification: 'B.Com + Taxation Certification',
            stream: 'commerce',
            avgSalary: '₹4-10 LPA',
            salaryNumeric: 700,
            jobType: 'Finance',
            demand: 'Medium',
            growthRate: '14%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Arts Stream (6 careers)
        {
            career: 'Teacher (PGT/TGT)',
            qualification: 'B.Ed/M.Ed + Graduation',
            stream: 'arts',
            avgSalary: '₹3-8 LPA',
            salaryNumeric: 550,
            jobType: 'Education',
            demand: 'High',
            growthRate: '10%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Journalist',
            qualification: 'BA/MA in Journalism',
            stream: 'arts',
            avgSalary: '₹3-9 LPA',
            salaryNumeric: 600,
            jobType: 'Media',
            demand: 'Medium',
            growthRate: '11%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Graphic Designer',
            qualification: 'BA/Diploma in Design',
            stream: 'arts',
            avgSalary: '₹3-8 LPA',
            salaryNumeric: 550,
            jobType: 'Creative',
            demand: 'Medium',
            growthRate: '15%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Lawyer',
            qualification: 'LLB + Bar Council Registration',
            stream: 'arts',
            avgSalary: '₹4-15 LPA',
            salaryNumeric: 950,
            jobType: 'Legal',
            demand: 'High',
            growthRate: '13%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Social Worker',
            qualification: 'BA/MA in Social Work',
            stream: 'arts',
            avgSalary: '₹3-6 LPA',
            salaryNumeric: 450,
            jobType: 'Social Service',
            demand: 'Medium',
            growthRate: '8%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Content Writer',
            qualification: 'BA in English/Mass Communication',
            stream: 'arts',
            avgSalary: '₹3-7 LPA',
            salaryNumeric: 500,
            jobType: 'Creative',
            demand: 'High',
            growthRate: '18%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Diploma Stream (4 careers)
        {
            career: 'Diploma Engineer',
            qualification: 'Diploma in Engineering',
            stream: 'diploma',
            avgSalary: '₹3-7 LPA',
            salaryNumeric: 500,
            jobType: 'Engineering',
            demand: 'Medium',
            growthRate: '12%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Lab Technician',
            qualification: 'Diploma in Medical Lab Technology',
            stream: 'diploma',
            avgSalary: '₹2.5-5 LPA',
            salaryNumeric: 375,
            jobType: 'Medical',
            demand: 'Medium',
            growthRate: '10%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Surveyor',
            qualification: 'Diploma in Civil Engineering',
            stream: 'diploma',
            avgSalary: '₹3-6 LPA',
            salaryNumeric: 450,
            jobType: 'Engineering',
            demand: 'Medium',
            growthRate: '9%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Computer Hardware Technician',
            qualification: 'Diploma in Computer Hardware',
            stream: 'diploma',
            avgSalary: '₹2.5-5 LPA',
            salaryNumeric: 375,
            jobType: 'IT',
            demand: 'Medium',
            growthRate: '11%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // ITI Stream (3 careers)
        {
            career: 'Electrician',
            qualification: '10th + ITI in Electrician',
            stream: 'iti',
            avgSalary: '₹2-5 LPA',
            salaryNumeric: 350,
            jobType: 'Skilled Trade',
            demand: 'High',
            growthRate: '12%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Mechanic',
            qualification: '10th + ITI in Mechanic',
            stream: 'iti',
            avgSalary: '₹2-4.5 LPA',
            salaryNumeric: 325,
            jobType: 'Skilled Trade',
            demand: 'High',
            growthRate: '10%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Welder',
            qualification: '10th + ITI in Welding',
            stream: 'iti',
            avgSalary: '₹2-4 LPA',
            salaryNumeric: 300,
            jobType: 'Skilled Trade',
            demand: 'Medium',
            growthRate: '9%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Government Stream (3 careers)
        {
            career: 'Government Officer (IAS/IPS)',
            qualification: 'Graduation + UPSC Civil Services',
            stream: 'government',
            avgSalary: '₹8-20 LPA',
            salaryNumeric: 1400,
            jobType: 'Government',
            demand: 'High',
            growthRate: '8%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Bank PO',
            qualification: 'Graduation + IBPS PO Exam',
            stream: 'government',
            avgSalary: '₹7-12 LPA',
            salaryNumeric: 950,
            jobType: 'Government',
            demand: 'High',
            growthRate: '10%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            career: 'Railway Officer',
            qualification: 'Graduation + Railway Recruitment Exam',
            stream: 'government',
            avgSalary: '₹6-11 LPA',
            salaryNumeric: 850,
            jobType: 'Government',
            demand: 'High',
            growthRate: '9%',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(careers).values(sampleCareers);
    
    console.log('✅ Careers seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});