import { db } from '@/db';
import { colleges } from '@/db/schema';

async function main() {
    const sampleColleges = [
        // ANANTAPUR DISTRICT - 10 colleges
        {
            name: 'JNTUA College of Engineering Anantapur',
            location: 'Ananthapuramu - Kalyandurg Rd, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Government',
            rating: 4.3,
            fees: '₹25,000 - ₹45,000/year',
            coursesOffered: ['B.Tech Computer Science', 'B.Tech Mechanical Engineering', 'B.Tech Electrical Engineering', 'B.Tech Civil Engineering', 'M.Tech', 'MBA'],
            contact: '08554-255600',
            email: 'principal@jntua.ac.in',
            website: 'https://jntua.ac.in',
            affiliation: 'JNTUA',
            latitude: 14.6819,
            longitude: 77.6006,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sri Krishnadevaraya University',
            location: 'NH-7, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'arts',
            type: 'Government',
            rating: 4.1,
            fees: '₹15,000 - ₹35,000/year',
            coursesOffered: ['BA', 'BSc', 'BCom', 'MA', 'MSc', 'MCom'],
            contact: '08554-255700',
            email: 'info@skuniversity.ac.in',
            website: 'https://skuniversity.ac.in',
            affiliation: 'UGC',
            latitude: 14.6450,
            longitude: 77.5850,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Government Polytechnic Anantapur',
            location: 'Kalyana Mandapam Road, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'diploma',
            type: 'Government',
            rating: 3.8,
            fees: '₹12,000 - ₹25,000/year',
            coursesOffered: ['Diploma in Mechanical Engineering', 'Diploma in Electrical Engineering', 'Diploma in Civil Engineering', 'Diploma in Electronics'],
            contact: '08554-273344',
            email: 'gptanantapur@sbtet.ap.gov.in',
            website: null,
            affiliation: 'State Board of Technical Education',
            latitude: 14.6800,
            longitude: 77.6100,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Annamacharya Institute of Technology and Sciences',
            location: 'Kadapa Road, Rajampet, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Private',
            rating: 4.0,
            fees: '₹75,000 - ₹1,20,000/year',
            coursesOffered: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical', 'M.Tech', 'MBA'],
            contact: '9440123456',
            email: 'info@aits.edu.in',
            website: 'https://aits.edu.in',
            affiliation: 'JNTUA',
            latitude: 14.1700,
            longitude: 78.8400,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Government ITI Anantapur',
            location: 'Industrial Area, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'iti',
            type: 'Government',
            rating: 3.5,
            fees: '₹5,000 - ₹15,000/year',
            coursesOffered: ['Fitter', 'Electrician', 'Welder', 'Turner'],
            contact: '08554-298765',
            email: 'itianantapur@apita.gov.in',
            website: null,
            affiliation: 'NCVT',
            latitude: 14.6900,
            longitude: 77.6200,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sree Vidyanikethan Engineering College',
            location: 'A. Rangampet, Tirupati Road, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Private',
            rating: 4.2,
            fees: '₹85,000 - ₹1,50,000/year',
            coursesOffered: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech EEE', 'M.Tech', 'MBA'],
            contact: '9876543210',
            email: 'admissions@svec.edu.in',
            website: 'https://svec.edu.in',
            affiliation: 'JNTUA',
            latitude: 14.7200,
            longitude: 77.6300,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Government Degree College Anantapur',
            location: 'College Road, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'commerce',
            type: 'Government',
            rating: 3.9,
            fees: '₹10,000 - ₹20,000/year',
            coursesOffered: ['B.Com', 'B.Com Computer Applications', 'B.Com Honours'],
            contact: '08554-244567',
            email: 'gdcanantapur@yahoo.com',
            website: null,
            affiliation: 'Sri Krishnadevaraya University',
            latitude: 14.6750,
            longitude: 77.5950,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Rural College of Pharmacy',
            location: 'Nagasamudram, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Private',
            rating: 3.7,
            fees: '₹60,000 - ₹95,000/year',
            coursesOffered: ['B.Pharmacy', 'D.Pharmacy', 'M.Pharmacy'],
            contact: '9123456789',
            email: 'info@ruralpharmacy.ac.in',
            website: 'https://ruralpharmacy.ac.in',
            affiliation: 'JNTUA',
            latitude: 14.7000,
            longitude: 77.6500,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'St. Johns College of Engineering and Technology',
            location: 'Yemmiganur Road, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'diploma',
            type: 'Private',
            rating: 3.4,
            fees: '₹40,000 - ₹70,000/year',
            coursesOffered: ['Diploma in Mechanical', 'Diploma in Civil', 'Diploma in ECE', 'Diploma in EEE'],
            contact: '9234567890',
            email: 'stjohns@sjcet.ac.in',
            website: null,
            affiliation: 'State Board of Technical Education',
            latitude: 14.6600,
            longitude: 77.5800,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Hindu College Anantapur',
            location: 'Subhash Road, Anantapur',
            district: 'Anantapur',
            state: 'Andhra Pradesh',
            stream: 'arts',
            type: 'Aided',
            rating: 3.6,
            fees: '₹15,000 - ₹30,000/year',
            coursesOffered: ['BA Economics', 'BA History', 'BA Political Science', 'BSc Mathematics'],
            contact: '08554-233445',
            email: 'hinducollegeantp@gmail.com',
            website: null,
            affiliation: 'Sri Krishnadevaraya University',
            latitude: 14.6850,
            longitude: 77.6050,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // KURNOOL DISTRICT - 10 colleges
        {
            name: 'Government Medical College Kurnool',
            location: 'Budhawarpet, Kurnool',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Government',
            rating: 4.4,
            fees: '₹35,000 - ₹50,000/year',
            coursesOffered: ['MBBS', 'MD', 'MS', 'Nursing'],
            contact: '08518-274444',
            email: 'gmckurnool@gmail.com',
            website: 'https://gmckurnool.ap.gov.in',
            affiliation: 'NTR University of Health Sciences',
            latitude: 15.8281,
            longitude: 78.0373,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'JNTUA College of Engineering Pulivendula',
            location: 'Pulivendula, YSR Kadapa Dist',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Government',
            rating: 4.0,
            fees: '₹20,000 - ₹40,000/year',
            coursesOffered: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical', 'B.Tech Civil'],
            contact: '08564-255100',
            email: 'principal.jntuacep@jntua.ac.in',
            website: 'https://jntuacep.ac.in',
            affiliation: 'JNTUA',
            latitude: 14.4212,
            longitude: 78.2249,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Government Polytechnic Kurnool',
            location: 'Station Road, Kurnool',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'diploma',
            type: 'Government',
            rating: 3.9,
            fees: '₹10,000 - ₹22,000/year',
            coursesOffered: ['Diploma in Mechanical', 'Diploma in Electrical', 'Diploma in Civil', 'Diploma in Computer Science'],
            contact: '08518-221122',
            email: 'gptkurnool@sbtet.ap.gov.in',
            website: null,
            affiliation: 'State Board of Technical Education',
            latitude: 15.8300,
            longitude: 78.0500,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'S V Engineering College for Women',
            location: 'Tirupati Road, Kurnool',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Private',
            rating: 3.8,
            fees: '₹65,000 - ₹1,10,000/year',
            coursesOffered: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech IT', 'MBA'],
            contact: '9345678901',
            email: 'svecw@gmail.com',
            website: 'https://svecw.edu.in',
            affiliation: 'JNTUA',
            latitude: 15.8400,
            longitude: 78.0600,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Government ITI Kurnool',
            location: 'Industrial Estate, Kurnool',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'iti',
            type: 'Government',
            rating: 3.7,
            fees: '₹6,000 - ₹18,000/year',
            coursesOffered: ['Electrician', 'Fitter', 'Mechanic Motor Vehicle', 'Plumber'],
            contact: '08518-234567',
            email: 'itikurnool@apita.gov.in',
            website: null,
            affiliation: 'NCVT',
            latitude: 15.8350,
            longitude: 78.0450,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Government Degree College Kurnool',
            location: 'Near Railway Station, Kurnool',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'commerce',
            type: 'Government',
            rating: 3.8,
            fees: '₹12,000 - ₹25,000/year',
            coursesOffered: ['B.Com', 'B.Com Computer Applications', 'B.Com Honours', 'BBA'],
            contact: '08518-256789',
            email: 'gdckurnool@gmail.com',
            website: null,
            affiliation: 'Rayalaseema University',
            latitude: 15.8200,
            longitude: 78.0300,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sree Rama Institute of Technology and Science',
            location: 'Penukonda Road, Kurnool',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'diploma',
            type: 'Private',
            rating: 3.3,
            fees: '₹35,000 - ₹65,000/year',
            coursesOffered: ['Diploma in Mechanical', 'Diploma in ECE', 'Diploma in Civil', 'Diploma in EEE'],
            contact: '9456789012',
            email: 'srits@gmail.com',
            website: null,
            affiliation: 'State Board of Technical Education',
            latitude: 15.8100,
            longitude: 77.9900,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'St. Theresas College for Women',
            location: 'Prakasam Road, Kurnool',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'arts',
            type: 'Aided',
            rating: 3.9,
            fees: '₹18,000 - ₹35,000/year',
            coursesOffered: ['BA', 'BSc', 'BCom', 'BCA'],
            contact: '08518-245678',
            email: 'sttheresaskurnool@gmail.com',
            website: null,
            affiliation: 'Rayalaseema University',
            latitude: 15.8250,
            longitude: 78.0350,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Vikas College of Engineering',
            location: 'Vijayawada Highway, Kurnool',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Private',
            rating: 3.5,
            fees: '₹55,000 - ₹90,000/year',
            coursesOffered: ['B.Tech CSE', 'B.Tech Mechanical', 'B.Tech Civil', 'MBA'],
            contact: '9567890123',
            email: 'vikas@vikaseng.ac.in',
            website: 'https://vikaseng.ac.in',
            affiliation: 'JNTUA',
            latitude: 15.8450,
            longitude: 78.0700,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'S V Arts College',
            location: 'Railway Station Road, Kurnool',
            district: 'Kurnool',
            state: 'Andhra Pradesh',
            stream: 'commerce',
            type: 'Aided',
            rating: 3.7,
            fees: '₹15,000 - ₹28,000/year',
            coursesOffered: ['B.Com', 'B.Com Computer Applications', 'BBA'],
            contact: '08518-267890',
            email: 'svarts@yahoo.com',
            website: null,
            affiliation: 'Rayalaseema University',
            latitude: 15.8220,
            longitude: 78.0320,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // KADAPA DISTRICT - 10 colleges
        {
            name: 'Yogi Vemana University',
            location: 'Vemanapuram, Kadapa',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'arts',
            type: 'Government',
            rating: 4.2,
            fees: '₹15,000 - ₹40,000/year',
            coursesOffered: ['BA', 'BSc', 'BCom', 'MA', 'MSc', 'MCom'],
            contact: '08562-289999',
            email: 'registrar@yogivemanauniversity.ac.in',
            website: 'https://yogivemanauniversity.ac.in',
            affiliation: 'UGC',
            latitude: 14.4673,
            longitude: 78.8241,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Rajiv Gandhi Institute of Medical Sciences',
            location: 'Kadapa',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Government',
            rating: 4.5,
            fees: '₹30,000 - ₹45,000/year',
            coursesOffered: ['MBBS', 'MD', 'MS', 'Nursing', 'Paramedical Courses'],
            contact: '08562-238888',
            email: 'rims.kadapa@gmail.com',
            website: 'https://rimskadapa.ap.gov.in',
            affiliation: 'NTR University of Health Sciences',
            latitude: 14.4700,
            longitude: 78.8300,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Government Polytechnic Kadapa',
            location: 'B N Reddy Nagar, Kadapa',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'diploma',
            type: 'Government',
            rating: 3.9,
            fees: '₹11,000 - ₹24,000/year',
            coursesOffered: ['Diploma in Mechanical', 'Diploma in Civil', 'Diploma in Electrical', 'Diploma in ECE'],
            contact: '08562-245678',
            email: 'gptkadapa@sbtet.ap.gov.in',
            website: null,
            affiliation: 'State Board of Technical Education',
            latitude: 14.4750,
            longitude: 78.8350,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Madanapalle Institute of Technology and Science',
            location: 'Angallu, Madanapalle, Chittoor',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Private',
            rating: 4.1,
            fees: '₹80,000 - ₹1,40,000/year',
            coursesOffered: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical', 'B.Tech Civil', 'M.Tech', 'MBA'],
            contact: '9678901234',
            email: 'info@mits.ac.in',
            website: 'https://mits.ac.in',
            affiliation: 'JNTUA',
            latitude: 13.5503,
            longitude: 78.5026,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Government ITI Kadapa',
            location: 'Industrial Area, Kadapa',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'iti',
            type: 'Government',
            rating: 3.6,
            fees: '₹5,500 - ₹16,000/year',
            coursesOffered: ['Fitter', 'Electrician', 'Welder', 'Turner', 'Mechanic Motor Vehicle'],
            contact: '08562-256789',
            email: 'itikadapa@apita.gov.in',
            website: null,
            affiliation: 'NCVT',
            latitude: 14.4800,
            longitude: 78.8400,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Priyadarshini College of Engineering',
            location: 'Nellore Road, Kadapa',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Private',
            rating: 3.6,
            fees: '₹60,000 - ₹1,00,000/year',
            coursesOffered: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical', 'MBA'],
            contact: '9789012345',
            email: 'priyadarshini@gmail.com',
            website: null,
            affiliation: 'JNTUA',
            latitude: 14.4600,
            longitude: 78.8150,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Government Degree College Kadapa',
            location: 'Gandhi Road, Kadapa',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'commerce',
            type: 'Government',
            rating: 3.8,
            fees: '₹10,000 - ₹22,000/year',
            coursesOffered: ['B.Com', 'B.Com Honours', 'BBA'],
            contact: '08562-267890',
            email: 'gdckadapa@gmail.com',
            website: null,
            affiliation: 'Yogi Vemana University',
            latitude: 14.4650,
            longitude: 78.8200,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sree Venkateswara Polytechnic College',
            location: 'Proddatur Road, Kadapa',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'diploma',
            type: 'Private',
            rating: 3.2,
            fees: '₹38,000 - ₹68,000/year',
            coursesOffered: ['Diploma in Mechanical', 'Diploma in Civil', 'Diploma in Electrical'],
            contact: '9890123456',
            email: 'svpolytechnic@gmail.com',
            website: null,
            affiliation: 'State Board of Technical Education',
            latitude: 14.4550,
            longitude: 78.8050,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Dr YSR College for Women',
            location: 'Near RTC Bus Stand, Kadapa',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'arts',
            type: 'Aided',
            rating: 3.9,
            fees: '₹16,000 - ₹32,000/year',
            coursesOffered: ['BA', 'BSc', 'BCom', 'BCA'],
            contact: '08562-278901',
            email: 'drysrcollege@gmail.com',
            website: null,
            affiliation: 'Yogi Vemana University',
            latitude: 14.4700,
            longitude: 78.8250,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Balaji Institute of Technology and Science',
            location: 'Nellore Highway, Kadapa',
            district: 'Kadapa',
            state: 'Andhra Pradesh',
            stream: 'science',
            type: 'Private',
            rating: 3.4,
            fees: '₹58,000 - ₹95,000/year',
            coursesOffered: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech EEE', 'MBA'],
            contact: '9901234567',
            email: 'info@bits-kadapa.ac.in',
            website: 'https://bits-kadapa.ac.in',
            affiliation: 'JNTUA',
            latitude: 14.4850,
            longitude: 78.8450,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(colleges).values(sampleColleges);
    
    console.log('✅ Colleges seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});