import { db } from '@/db';
import { courses } from '@/db/schema';

async function main() {
    const sampleCourses = [
        // Science Stream (id: 1) - 8 courses
        {
            streamId: 1,
            name: 'Bachelor of Technology (B.Tech) in Computer Science Engineering',
            duration: '4 years',
            fees: '₹80,000 - ₹3,00,000/year',
            eligibility: '10+2 with Physics, Chemistry, and Mathematics with minimum 50% marks',
            description: 'B.Tech in Computer Science Engineering is one of the most sought-after engineering courses focusing on computer programming, software development, and emerging technologies. Students learn programming languages, data structures, algorithms, artificial intelligence, and machine learning.',
            careerRoles: ['Software Developer', 'Data Scientist', 'Machine Learning Engineer', 'System Analyst', 'Cloud Architect', 'Cybersecurity Specialist'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'Bachelor of Medicine and Bachelor of Surgery (MBBS)',
            duration: '5.5 years (including 1 year internship)',
            fees: '₹50,000 - ₹25,00,000/year',
            eligibility: '10+2 with Physics, Chemistry, and Biology with minimum 50% marks and NEET qualification',
            description: 'MBBS is the primary medical degree for becoming a doctor in India. The course covers comprehensive medical education including anatomy, physiology, pharmacology, and clinical practice. Students undergo rigorous training in hospitals and clinics.',
            careerRoles: ['Medical Doctor', 'Surgeon', 'General Physician', 'Medical Researcher', 'Public Health Officer', 'Hospital Administrator'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'Bachelor of Technology (B.Tech) in Electrical Engineering',
            duration: '4 years',
            fees: '₹70,000 - ₹2,50,000/year',
            eligibility: '10+2 with Physics, Chemistry, and Mathematics with minimum 50% marks',
            description: 'B.Tech in Electrical Engineering deals with the study of electricity, electronics, and electromagnetism. Students learn about power systems, electrical machines, control systems, and renewable energy technologies.',
            careerRoles: ['Electrical Engineer', 'Power System Engineer', 'Control System Engineer', 'Renewable Energy Consultant', 'Electrical Design Engineer', 'Transmission Engineer'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'Bachelor of Dental Surgery (BDS)',
            duration: '5 years (including 1 year internship)',
            fees: '₹50,000 - ₹5,00,000/year',
            eligibility: '10+2 with Physics, Chemistry, and Biology with minimum 50% marks and NEET qualification',
            description: 'BDS is an undergraduate dental degree program that trains students in oral health care, dental surgery, and patient management. The course includes theoretical knowledge and practical clinical training in dental hospitals.',
            careerRoles: ['Dentist', 'Oral Surgeon', 'Dental Consultant', 'Dental Researcher', 'Public Health Dentist', 'Forensic Odontologist'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'Bachelor of Science (B.Sc) in Nursing',
            duration: '4 years',
            fees: '₹30,000 - ₹1,50,000/year',
            eligibility: '10+2 with Physics, Chemistry, and Biology with minimum 45% marks',
            description: 'B.Sc Nursing is a professional degree that prepares students for a career in healthcare as registered nurses. The curriculum covers anatomy, physiology, medical-surgical nursing, community health nursing, and psychiatric nursing.',
            careerRoles: ['Registered Nurse', 'Staff Nurse', 'Community Health Nurse', 'Nursing Supervisor', 'ICU Specialist', 'Nursing Educator'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'Bachelor of Pharmacy (B.Pharm)',
            duration: '4 years',
            fees: '₹40,000 - ₹1,80,000/year',
            eligibility: '10+2 with Physics, Chemistry, and Mathematics/Biology with minimum 50% marks',
            description: 'B.Pharm is an undergraduate program in pharmaceutical sciences covering drug composition, medicinal chemistry, pharmacology, and pharmaceutical technology. Students learn about drug development, manufacturing, and distribution.',
            careerRoles: ['Pharmacist', 'Drug Inspector', 'Medical Representative', 'Pharmaceutical Researcher', 'Quality Control Officer', 'Hospital Pharmacist'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'Bachelor of Technology (B.Tech) in Mechanical Engineering',
            duration: '4 years',
            fees: '₹75,000 - ₹2,80,000/year',
            eligibility: '10+2 with Physics, Chemistry, and Mathematics with minimum 50% marks',
            description: 'B.Tech in Mechanical Engineering focuses on the design, manufacturing, and maintenance of mechanical systems. Students study thermodynamics, mechanics, robotics, and automotive engineering.',
            careerRoles: ['Mechanical Engineer', 'Production Engineer', 'Automotive Engineer', 'Design Engineer', 'Maintenance Engineer', 'CAD/CAM Engineer'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'Bachelor of Technology (B.Tech) in Civil Engineering',
            duration: '4 years',
            fees: '₹65,000 - ₹2,40,000/year',
            eligibility: '10+2 with Physics, Chemistry, and Mathematics with minimum 50% marks',
            description: 'B.Tech in Civil Engineering deals with the design, construction, and maintenance of infrastructure projects like buildings, roads, bridges, and dams. Students learn structural engineering, environmental engineering, and construction management.',
            careerRoles: ['Civil Engineer', 'Structural Engineer', 'Construction Manager', 'Highway Engineer', 'Urban Planner', 'Site Engineer'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Commerce Stream (id: 2) - 7 courses
        {
            streamId: 2,
            name: 'Bachelor of Commerce (B.Com)',
            duration: '3 years',
            fees: '₹15,000 - ₹80,000/year',
            eligibility: '10+2 in Commerce stream with minimum 45% marks',
            description: 'B.Com is an undergraduate degree focusing on accounting, finance, business law, and economics. It provides a strong foundation for careers in finance, banking, and business management.',
            careerRoles: ['Accountant', 'Tax Consultant', 'Financial Analyst', 'Auditor', 'Banking Professional', 'Stock Broker'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'Bachelor of Business Administration (BBA)',
            duration: '3 years',
            fees: '₹30,000 - ₹1,50,000/year',
            eligibility: '10+2 in any stream with minimum 50% marks',
            description: 'BBA is a management degree that prepares students for leadership roles in business. The course covers marketing, human resources, finance, operations management, and entrepreneurship.',
            careerRoles: ['Business Manager', 'Marketing Executive', 'HR Manager', 'Business Analyst', 'Operations Manager', 'Entrepreneur'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'Chartered Accountancy (CA)',
            duration: '4-5 years',
            fees: '₹1,50,000 - ₹3,00,000 (total course)',
            eligibility: '10+2 in Commerce with minimum 50% marks or graduation',
            description: 'CA is the most prestigious professional qualification in accounting and finance. The course involves rigorous training in auditing, taxation, financial reporting, and corporate laws through articleship and examinations.',
            careerRoles: ['Chartered Accountant', 'Tax Advisor', 'Financial Consultant', 'Corporate Auditor', 'CFO', 'Investment Banker'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'Company Secretary (CS)',
            duration: '3-4 years',
            fees: '₹60,000 - ₹1,20,000 (total course)',
            eligibility: '10+2 in any stream with minimum 50% marks or graduation',
            description: 'CS is a professional course focusing on corporate law, governance, and compliance. Company Secretaries ensure that companies comply with legal and regulatory requirements.',
            careerRoles: ['Company Secretary', 'Compliance Officer', 'Corporate Lawyer', 'Legal Advisor', 'Governance Consultant', 'Corporate Affairs Manager'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'Cost and Management Accountant (CMA)',
            duration: '3-4 years',
            fees: '₹70,000 - ₹1,50,000 (total course)',
            eligibility: '10+2 in Commerce with minimum 50% marks or graduation',
            description: 'CMA is a professional qualification focused on cost accounting, financial management, and strategic management. CMAs specialize in cost control, budgeting, and financial planning for organizations.',
            careerRoles: ['Cost Accountant', 'Management Accountant', 'Financial Controller', 'Budget Analyst', 'Internal Auditor', 'Financial Planner'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'Bachelor of Commerce (B.Com) in Banking and Insurance',
            duration: '3 years',
            fees: '₹20,000 - ₹90,000/year',
            eligibility: '10+2 in Commerce stream with minimum 45% marks',
            description: 'This specialized B.Com program focuses on banking operations, insurance products, risk management, and financial services. Students gain expertise in banking systems, insurance policies, and investment management.',
            careerRoles: ['Bank Officer', 'Insurance Agent', 'Loan Officer', 'Investment Advisor', 'Risk Manager', 'Financial Services Representative'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'Bachelor of Commerce (B.Com) in Accounting and Finance',
            duration: '3 years',
            fees: '₹18,000 - ₹85,000/year',
            eligibility: '10+2 in Commerce stream with minimum 45% marks',
            description: 'This B.Com specialization provides in-depth knowledge of accounting principles, financial management, taxation, and corporate finance. It prepares students for professional accounting careers and further certifications.',
            careerRoles: ['Financial Accountant', 'Finance Manager', 'Tax Consultant', 'Treasury Manager', 'Credit Analyst', 'Investment Banking Analyst'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Arts Stream (id: 3) - 7 courses
        {
            streamId: 3,
            name: 'Bachelor of Arts (BA) in English Literature',
            duration: '3 years',
            fees: '₹10,000 - ₹50,000/year',
            eligibility: '10+2 in any stream with minimum 45% marks',
            description: 'BA in English Literature focuses on the study of English language, literature, poetry, drama, and prose. Students develop critical thinking, communication, and analytical skills through the study of classic and contemporary works.',
            careerRoles: ['Content Writer', 'Journalist', 'Editor', 'Teacher', 'Copywriter', 'Public Relations Officer'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'Bachelor of Education (B.Ed)',
            duration: '2 years',
            fees: '₹30,000 - ₹1,20,000/year',
            eligibility: 'Graduation in any stream with minimum 50% marks',
            description: 'B.Ed is a professional teaching degree that prepares graduates to become school teachers. The course covers educational psychology, teaching methodologies, curriculum development, and classroom management.',
            careerRoles: ['School Teacher', 'Education Counselor', 'Curriculum Designer', 'Academic Coordinator', 'Educational Administrator', 'Private Tutor'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'Bachelor of Mass Communication and Journalism (BMCJ)',
            duration: '3 years',
            fees: '₹40,000 - ₹1,80,000/year',
            eligibility: '10+2 in any stream with minimum 50% marks',
            description: 'BMCJ is a professional course covering print journalism, broadcast media, digital media, advertising, and public relations. Students learn news writing, video production, media ethics, and communication strategies.',
            careerRoles: ['Journalist', 'News Anchor', 'Radio Jockey', 'Content Creator', 'Media Planner', 'Social Media Manager'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'Bachelor of Fine Arts (BFA)',
            duration: '4 years',
            fees: '₹30,000 - ₹1,50,000/year',
            eligibility: '10+2 in any stream with minimum 45% marks and portfolio/entrance test',
            description: 'BFA is a specialized degree in visual arts covering painting, sculpture, applied arts, and graphic design. Students develop creative skills and artistic expression through practical training and theory.',
            careerRoles: ['Artist', 'Graphic Designer', 'Art Director', 'Illustrator', 'Animation Artist', 'Gallery Curator'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'Bachelor of Hotel Management (BHM)',
            duration: '4 years',
            fees: '₹80,000 - ₹3,50,000/year',
            eligibility: '10+2 in any stream with minimum 50% marks',
            description: 'BHM is a professional degree in hospitality management covering hotel operations, food and beverage service, housekeeping, front office management, and culinary arts. Students undergo industrial training in reputed hotels.',
            careerRoles: ['Hotel Manager', 'Restaurant Manager', 'Event Manager', 'Chef', 'Front Office Manager', 'Hospitality Consultant'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'Bachelor of Arts (BA) in Psychology',
            duration: '3 years',
            fees: '₹15,000 - ₹70,000/year',
            eligibility: '10+2 in any stream with minimum 45% marks',
            description: 'BA in Psychology covers human behavior, mental processes, cognitive psychology, and social psychology. Students learn about psychological theories, research methods, and counseling techniques.',
            careerRoles: ['Counselor', 'Clinical Psychologist', 'HR Professional', 'Organizational Psychologist', 'School Counselor', 'Research Analyst'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'Bachelor of Arts (BA) in History',
            duration: '3 years',
            fees: '₹10,000 - ₹45,000/year',
            eligibility: '10+2 in any stream with minimum 45% marks',
            description: 'BA in History involves the study of ancient, medieval, and modern history of India and the world. Students develop research skills, critical analysis, and understanding of historical events and their impact on society.',
            careerRoles: ['History Teacher', 'Museum Curator', 'Archaeologist', 'Archivist', 'Heritage Manager', 'Research Scholar'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Diploma Stream (id: 4) - 8 courses
        {
            streamId: 4,
            name: 'Diploma in Computer Engineering',
            duration: '3 years',
            fees: '₹20,000 - ₹80,000/year',
            eligibility: '10th pass with minimum 35% marks',
            description: 'This diploma program provides foundational knowledge in computer hardware, software, programming, and networking. Students learn programming languages, database management, and web development.',
            careerRoles: ['Junior Programmer', 'Web Developer', 'Technical Support Engineer', 'Network Administrator', 'Computer Operator', 'Database Assistant'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Diploma in Mechanical Engineering',
            duration: '3 years',
            fees: '₹18,000 - ₹75,000/year',
            eligibility: '10th pass with minimum 35% marks',
            description: 'This diploma covers fundamentals of mechanical systems, manufacturing processes, machine design, and industrial automation. Students gain practical skills in workshop and laboratory settings.',
            careerRoles: ['Mechanical Technician', 'Production Supervisor', 'Quality Inspector', 'Maintenance Engineer', 'CAD Operator', 'Workshop Supervisor'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Diploma in Civil Engineering',
            duration: '3 years',
            fees: '₹17,000 - ₹70,000/year',
            eligibility: '10th pass with minimum 35% marks',
            description: 'This diploma program teaches construction techniques, surveying, structural design, and building materials. Students learn to assist in planning, designing, and supervising construction projects.',
            careerRoles: ['Junior Civil Engineer', 'Site Supervisor', 'Surveyor', 'Estimation Engineer', 'Construction Inspector', 'Draftsman'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Diploma in Electrical Engineering',
            duration: '3 years',
            fees: '₹18,000 - ₹72,000/year',
            eligibility: '10th pass with minimum 35% marks',
            description: 'This diploma covers electrical circuits, power systems, electrical machines, and control systems. Students learn installation, maintenance, and troubleshooting of electrical equipment and systems.',
            careerRoles: ['Electrical Technician', 'Maintenance Engineer', 'Panel Operator', 'Wireman', 'Substation Operator', 'Electrical Supervisor'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Diploma in Pharmacy (D.Pharm)',
            duration: '2 years',
            fees: '₹25,000 - ₹90,000/year',
            eligibility: '10th pass with minimum 50% marks in Science',
            description: 'D.Pharm is a professional diploma in pharmaceutical sciences covering drug composition, pharmacology, and pharmacy practice. Graduates can work as registered pharmacists after completing the course.',
            careerRoles: ['Pharmacist', 'Medical Representative', 'Drug Inspector', 'Pharmacy Store Manager', 'Hospital Pharmacist', 'Quality Control Assistant'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Diploma in Agriculture',
            duration: '2 years',
            fees: '₹10,000 - ₹40,000/year',
            eligibility: '10th pass with minimum 35% marks',
            description: 'This diploma provides knowledge of agricultural practices, crop production, soil management, and farm machinery. Students learn modern farming techniques and agricultural technologies.',
            careerRoles: ['Agricultural Officer', 'Farm Supervisor', 'Seed Analyst', 'Agriculture Extension Officer', 'Farm Manager', 'Agricultural Technician'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Diploma in Electronics and Communication Engineering',
            duration: '3 years',
            fees: '₹19,000 - ₹78,000/year',
            eligibility: '10th pass with minimum 35% marks',
            description: 'This diploma covers electronic circuits, communication systems, microprocessors, and embedded systems. Students gain skills in installation and maintenance of electronic equipment and communication devices.',
            careerRoles: ['Electronics Technician', 'Telecom Engineer', 'Service Engineer', 'PCB Designer', 'Network Technician', 'Radio Engineer'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Diploma in Automobile Engineering',
            duration: '3 years',
            fees: '₹20,000 - ₹85,000/year',
            eligibility: '10th pass with minimum 35% marks',
            description: 'This diploma focuses on vehicle design, automotive systems, engine mechanics, and vehicle maintenance. Students learn about modern automobile technology and electric vehicles.',
            careerRoles: ['Automobile Technician', 'Service Advisor', 'Showroom Manager', 'Production Engineer', 'Quality Control Inspector', 'Workshop Supervisor'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // ITI Stream (id: 5) - 8 courses
        {
            streamId: 5,
            name: 'ITI Electrician',
            duration: '2 years',
            fees: '₹5,000 - ₹25,000 (total course)',
            eligibility: '10th pass',
            description: 'ITI Electrician course trains students in electrical wiring, installation, maintenance, and repair of electrical equipment. Students learn safety procedures and hands-on electrical work.',
            careerRoles: ['Electrician', 'Wireman', 'Electrical Contractor', 'Maintenance Worker', 'Panel Operator', 'Power Plant Technician'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'ITI Fitter',
            duration: '2 years',
            fees: '₹5,000 - ₹22,000 (total course)',
            eligibility: '10th pass',
            description: 'ITI Fitter course provides training in fitting, assembly, and maintenance of machinery and mechanical systems. Students learn to work with hand tools, measuring instruments, and machine tools.',
            careerRoles: ['Fitter', 'Machine Operator', 'Maintenance Mechanic', 'Workshop Technician', 'Assembly Worker', 'Production Operator'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'ITI Welder',
            duration: '1 year',
            fees: '₹4,000 - ₹20,000 (total course)',
            eligibility: '10th pass',
            description: 'ITI Welder course trains students in various welding techniques including arc welding, gas welding, and modern welding technologies. Students gain practical skills in metal joining and fabrication.',
            careerRoles: ['Welder', 'Fabricator', 'Structural Welder', 'Pipe Welder', 'Maintenance Welder', 'Welding Inspector'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'ITI Mechanic Motor Vehicle',
            duration: '2 years',
            fees: '₹6,000 - ₹28,000 (total course)',
            eligibility: '10th pass',
            description: 'This ITI course covers automobile mechanics, engine repair, vehicle maintenance, and diagnostic procedures. Students learn to service and repair cars, trucks, and other motor vehicles.',
            careerRoles: ['Motor Vehicle Mechanic', 'Auto Mechanic', 'Service Technician', 'Garage Manager', 'Vehicle Inspector', 'Workshop Supervisor'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'ITI Computer Operator and Programming Assistant (COPA)',
            duration: '1 year',
            fees: '₹5,000 - ₹24,000 (total course)',
            eligibility: '10th pass',
            description: 'ITI COPA course provides training in computer operations, basic programming, office applications, and internet usage. Students learn MS Office, data entry, and fundamental programming concepts.',
            careerRoles: ['Computer Operator', 'Data Entry Operator', 'Office Assistant', 'DTP Operator', 'Junior Programmer', 'IT Support Staff'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'ITI Plumber',
            duration: '1 year',
            fees: '₹4,000 - ₹18,000 (total course)',
            eligibility: '10th pass',
            description: 'ITI Plumber course trains students in installation, maintenance, and repair of plumbing systems including water supply, drainage, and sanitation systems. Students learn pipe fitting, valve installation, and leak detection.',
            careerRoles: ['Plumber', 'Pipe Fitter', 'Sanitary Inspector', 'Water Supply Technician', 'Plumbing Contractor', 'Maintenance Plumber'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'ITI Draughtsman (Civil)',
            duration: '2 years',
            fees: '₹5,500 - ₹26,000 (total course)',
            eligibility: '10th pass',
            description: 'ITI Draughtsman Civil course trains students in technical drawing, architectural drafting, and CAD software. Students learn to prepare construction drawings, structural plans, and building layouts.',
            careerRoles: ['Draughtsman', 'CAD Operator', 'Technical Draftsperson', 'Estimation Engineer', 'Planning Assistant', 'Design Assistant'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'ITI Turner',
            duration: '2 years',
            fees: '₹5,000 - ₹23,000 (total course)',
            eligibility: '10th pass',
            description: 'ITI Turner course provides training in operating lathe machines and manufacturing cylindrical parts with precision. Students learn metal cutting, threading, and machining operations.',
            careerRoles: ['Turner', 'Lathe Operator', 'CNC Operator', 'Machine Operator', 'Production Operator', 'Quality Inspector'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Government Stream (id: 6) - 7 courses
        {
            streamId: 6,
            name: 'SSC Combined Graduate Level (CGL) Preparation',
            duration: '6 months - 1 year',
            fees: '₹15,000 - ₹50,000',
            eligibility: 'Graduation in any stream',
            description: 'SSC CGL is one of the most popular government exams for recruitment to Group B and C posts in various government ministries and departments. This preparation course covers quantitative aptitude, reasoning, English, and general awareness.',
            careerRoles: ['Income Tax Inspector', 'Excise Inspector', 'Assistant Audit Officer', 'Statistical Investigator', 'Inspector in Central Bureau of Investigation', 'Sub Inspector in CBI'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'Banking Exams (IBPS PO/Clerk/SO) Preparation',
            duration: '6 months - 1 year',
            fees: '₹12,000 - ₹45,000',
            eligibility: 'Graduation in any stream',
            description: 'Comprehensive preparation for IBPS and bank recruitment exams covering reasoning, quantitative aptitude, English, general awareness, and computer knowledge. Special focus on banking and financial awareness.',
            careerRoles: ['Bank Probationary Officer', 'Bank Clerk', 'Specialist Officer', 'Bank Manager', 'Assistant Manager', 'Credit Officer'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'Railway Recruitment Board (RRB) Preparation',
            duration: '4 months - 1 year',
            fees: '₹10,000 - ₹40,000',
            eligibility: '10th pass to Graduation (varies by post)',
            description: 'Preparation for various Railway recruitment exams including NTPC, Group D, ALP, and Technician posts. Covers mathematics, reasoning, general science, and current affairs specific to Railway exams.',
            careerRoles: ['Station Master', 'Commercial Apprentice', 'Ticket Collector', 'Train Clerk', 'Junior Accountant', 'Goods Guard'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'State Police Constable and SI Preparation',
            duration: '4 months - 8 months',
            fees: '₹8,000 - ₹35,000',
            eligibility: '10+2 to Graduation (varies by state)',
            description: 'Complete preparation for state police recruitment covering written exam, physical fitness, and interview. Includes reasoning, general knowledge, numerical ability, and state-specific syllabus.',
            careerRoles: ['Police Constable', 'Sub Inspector', 'Head Constable', 'Assistant Sub Inspector', 'Traffic Police', 'Crime Branch Officer'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'Defence Services (Army/Navy/Air Force) Preparation',
            duration: '6 months - 1 year',
            fees: '₹10,000 - ₹45,000',
            eligibility: '10+2 to Graduation (varies by post)',
            description: 'Preparation for various defence recruitment exams including soldier, technical entry, and officer rank examinations. Covers academics, physical fitness, and personality development.',
            careerRoles: ['Army Soldier', 'Navy Sailor', 'Air Force Airman', 'Technical Entry Officer', 'Clerk in Defence', 'Tradesman'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'State and Central Government Teaching (TET/CTET) Preparation',
            duration: '4 months - 8 months',
            fees: '₹12,000 - ₹40,000',
            eligibility: 'Graduation with B.Ed or D.Ed',
            description: 'Comprehensive preparation for Teacher Eligibility Tests covering child development, pedagogy, language skills, mathematics, and environmental studies. Separate modules for primary and upper primary levels.',
            careerRoles: ['Government School Teacher', 'Primary Teacher', 'Upper Primary Teacher', 'Language Teacher', 'Mathematics Teacher', 'Science Teacher'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'State Public Service Commission (State PSC) Preparation',
            duration: '1 year - 2 years',
            fees: '₹20,000 - ₹80,000',
            eligibility: 'Graduation in any stream',
            description: 'Complete preparation for state civil services exams covering preliminary, mains, and interview stages. Includes history, geography, polity, economics, current affairs, and state-specific topics.',
            careerRoles: ['Deputy Collector', 'Deputy Superintendent of Police', 'Block Development Officer', 'Assistant Commissioner', 'Tehsildar', 'Executive Magistrate'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(courses).values(sampleCourses);
    
    console.log('✅ Courses seeder completed successfully - 45 courses added across all 6 streams');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});