import { db } from '@/db';
import { exams } from '@/db/schema';

async function main() {
    const sampleExams = [
        // Science stream (id: 1) - 8 exams
        {
            streamId: 1,
            name: 'JEE Main',
            month: 'January, April',
            difficulty: 'Hard',
            eligibility: '10+2 pass with minimum 75% aggregate in Physics, Chemistry, and Mathematics',
            description: 'Joint Entrance Examination (Main) is conducted by NTA for admission to undergraduate engineering programs at NITs, IIITs, and other centrally funded technical institutions. It serves as a qualifying exam for JEE Advanced.',
            registrationLink: 'https://jeemain.nta.nic.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'JEE Advanced',
            month: 'May',
            difficulty: 'Hard',
            eligibility: 'Qualified JEE Main with top 2,50,000 rank and 10+2 pass with 75% in PCM',
            description: 'JEE Advanced is the gateway to IITs (Indian Institutes of Technology). Only top JEE Main qualifiers are eligible. It is considered one of the toughest engineering entrance exams in the world with highly competitive questions.',
            registrationLink: 'https://jeeadv.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'NEET UG',
            month: 'May',
            difficulty: 'Hard',
            eligibility: '10+2 pass with Physics, Chemistry, Biology/Biotechnology with minimum 50% marks',
            description: 'National Eligibility cum Entrance Test is the single entrance exam for admission to MBBS, BDS, AYUSH and other medical courses in India. Conducted by NTA, it is mandatory for all medical aspirants.',
            registrationLink: 'https://neet.nta.nic.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'AP EAMCET',
            month: 'May',
            difficulty: 'Medium',
            eligibility: '10+2 pass with PCM/PCB from recognized board in Andhra Pradesh',
            description: 'Andhra Pradesh Engineering, Agriculture and Medical Common Entrance Test is a state-level examination for admission to engineering, agriculture, and pharmacy courses in AP. Conducted by JNTU Kakinada on behalf of APSCHE.',
            registrationLink: 'https://sche.ap.gov.in/eamcet',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'BITSAT',
            month: 'June',
            difficulty: 'Hard',
            eligibility: '10+2 pass with minimum 75% aggregate in PCM and English',
            description: 'Birla Institute of Technology and Science Admission Test is conducted for admission to integrated first degree programmes at BITS Pilani campuses. It is a computer-based test known for its speed and accuracy requirements.',
            registrationLink: 'https://www.bitsadmission.com',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'VITEEE',
            month: 'April',
            difficulty: 'Medium',
            eligibility: '10+2 pass with minimum 60% aggregate in PCM and English',
            description: 'VIT Engineering Entrance Examination is conducted by Vellore Institute of Technology for admission to B.Tech programs across its campuses. It is a computer-based test with questions from Physics, Chemistry, Mathematics, and English.',
            registrationLink: 'https://viteee.vit.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'KIITEE',
            month: 'April',
            difficulty: 'Medium',
            eligibility: '10+2 pass with Physics, Chemistry, Mathematics with minimum 60% marks',
            description: 'Kalinga Institute of Industrial Technology Entrance Examination is conducted for admission to B.Tech, B.Arch, and other undergraduate programs at KIIT University. It is an online computer-based test.',
            registrationLink: 'https://kiitee.kiit.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 1,
            name: 'SRMJEEE',
            month: 'April-May',
            difficulty: 'Medium',
            eligibility: '10+2 pass with minimum 50% in PCM with English as a subject',
            description: 'SRM Joint Engineering Entrance Examination is conducted for admission to B.Tech programs at SRM Institute of Science and Technology. The exam tests aptitude in Physics, Chemistry, Mathematics, and English comprehension.',
            registrationLink: 'https://www.srmist.edu.in/admission',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Commerce stream (id: 2) - 6 exams
        {
            streamId: 2,
            name: 'CA Foundation',
            month: 'May, November',
            difficulty: 'Hard',
            eligibility: '10+2 pass in Commerce or any stream with registration with ICAI',
            description: 'Chartered Accountancy Foundation is the entry-level exam for CA course conducted by ICAI. It tests fundamentals of accounting, business laws, economics, and mathematics. Passing this is the first step toward becoming a Chartered Accountant.',
            registrationLink: 'https://www.icai.org',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'IPMAT',
            month: 'June',
            difficulty: 'Hard',
            eligibility: '10+2 pass with minimum 60% marks (55% for SC/ST/PwD)',
            description: 'Integrated Program in Management Aptitude Test is conducted by IIM Indore for admission to its 5-year Integrated Programme in Management. It assesses quantitative ability, verbal ability, and logical reasoning skills.',
            registrationLink: 'https://www.iimidr.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'CLAT',
            month: 'December',
            difficulty: 'Hard',
            eligibility: '10+2 pass with minimum 45% marks (40% for SC/ST) for UG law programs',
            description: 'Common Law Admission Test is conducted for admission to undergraduate and postgraduate law programs at 22 National Law Universities across India. It tests English, current affairs, legal reasoning, logical reasoning, and quantitative techniques.',
            registrationLink: 'https://consortiumofnlus.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'NPAT',
            month: 'May-June',
            difficulty: 'Medium',
            eligibility: '10+2 pass with minimum 50% marks for UG programs',
            description: 'NMIMS Programs After Twelfth is conducted by SVKM\'s NMIMS for admission to its undergraduate programs in Management, Commerce, Economics, Liberal Arts, Science, Law, and Design across its campuses.',
            registrationLink: 'https://npat.nmims.edu',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'CUET',
            month: 'May',
            difficulty: 'Medium',
            eligibility: '10+2 pass from recognized board for undergraduate programs',
            description: 'Common University Entrance Test is conducted by NTA for admission to undergraduate programs in central universities, state universities, and deemed universities across India. Students can apply to multiple universities with a single test.',
            registrationLink: 'https://cuet.samarth.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 2,
            name: 'SET',
            month: 'May',
            difficulty: 'Medium',
            eligibility: '10+2 pass with minimum 50% marks for BBA and other management programs',
            description: 'Symbiosis Entrance Test is conducted for admission to undergraduate programs in Management, Computer Studies, Economics, Liberal Arts, and Design at Symbiosis International University campuses. It includes objective and descriptive sections.',
            registrationLink: 'https://www.set-test.org',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Arts stream (id: 3) - 6 exams
        {
            streamId: 3,
            name: 'CUET UG Arts',
            month: 'May',
            difficulty: 'Medium',
            eligibility: '10+2 pass from recognized board for Arts/Humanities programs',
            description: 'Common University Entrance Test for Arts and Humanities programs provides a single entrance gateway to BA, BSc, and other undergraduate liberal arts programs across central and participating universities in India.',
            registrationLink: 'https://cuet.samarth.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'BHU UET',
            month: 'May-June',
            difficulty: 'Medium',
            eligibility: '10+2 pass with relevant subjects for chosen BA/BSc program',
            description: 'Banaras Hindu University Undergraduate Entrance Test is conducted for admission to various undergraduate programs in Arts, Social Sciences, Science, and other streams. BHU is one of the largest residential universities in Asia.',
            registrationLink: 'https://www.bhu.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'JMI Entrance',
            month: 'June',
            difficulty: 'Medium',
            eligibility: '10+2 pass with minimum 50% marks for BA/BSc programs',
            description: 'Jamia Millia Islamia conducts entrance tests for admission to undergraduate programs in Arts, Social Sciences, Languages, and Humanities. The university is known for its strong liberal arts and social science departments.',
            registrationLink: 'https://www.jmicoe.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'DU JAT',
            month: 'June',
            difficulty: 'Medium',
            eligibility: '10+2 pass with minimum 50% marks for BA (Journalism)',
            description: 'Delhi University Joint Admission Test for Journalism is conducted for admission to BA programs in Journalism and Mass Communication. It tests general awareness, current affairs, English comprehension, and logical reasoning.',
            registrationLink: 'https://www.du.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'AUCET',
            month: 'June',
            difficulty: 'Medium',
            eligibility: '10+2 pass for admission to Andhra University undergraduate programs',
            description: 'Andhra University Common Entrance Test is conducted for admission to various undergraduate programs including BA, BSc, and BBA at Andhra University and its affiliated colleges in Andhra Pradesh.',
            registrationLink: 'https://www.andhrauniversity.edu.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 3,
            name: 'JNUEE',
            month: 'December',
            difficulty: 'Hard',
            eligibility: '10+2 pass with minimum 45% for undergraduate programs in Arts/Humanities',
            description: 'Jawaharlal Nehru University Entrance Examination is conducted for admission to BA programs in Languages, Social Sciences, and Liberal Arts. JNU is renowned for its academic excellence and research in social sciences.',
            registrationLink: 'https://www.jnu.ac.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Diploma stream (id: 4) - 6 exams
        {
            streamId: 4,
            name: 'AP POLYCET',
            month: 'April',
            difficulty: 'Medium',
            eligibility: '10th pass or equivalent from recognized board',
            description: 'Andhra Pradesh Polytechnic Common Entrance Test is conducted by SBTET for admission to Diploma courses in Engineering and Non-Engineering streams in government and private polytechnics across Andhra Pradesh.',
            registrationLink: 'https://sbtet.ap.gov.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'TS POLYCET',
            month: 'April-May',
            difficulty: 'Medium',
            eligibility: '10th class pass or equivalent examination',
            description: 'Telangana State Polytechnic Common Entrance Test is conducted by SBTET for admission to Diploma programs in Engineering and Non-Engineering in polytechnic colleges across Telangana state.',
            registrationLink: 'https://sbtet.telangana.gov.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Karnataka DCET',
            month: 'June',
            difficulty: 'Medium',
            eligibility: '10th pass with Diploma in Engineering/Technology from recognized institution',
            description: 'Karnataka Diploma Common Entrance Test is conducted for lateral entry admission to second year of BE/B.Tech courses for diploma holders in Karnataka. Conducted by Karnataka Examinations Authority.',
            registrationLink: 'https://kea.kar.nic.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Delhi CET Polytechnic',
            month: 'May',
            difficulty: 'Medium',
            eligibility: '10th pass with minimum 35% marks from recognized board',
            description: 'Delhi Polytechnic Common Entrance Test is conducted for admission to Diploma courses in various branches of Engineering and Technology in government-aided polytechnics in Delhi.',
            registrationLink: 'https://delhi.gov.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'Maharashtra Polytechnic',
            month: 'May',
            difficulty: 'Medium',
            eligibility: '10th pass or equivalent from any recognized board',
            description: 'Maharashtra Polytechnic Entrance Examination is conducted by DTE Maharashtra for admission to first year of three-year full-time Diploma courses in Engineering and Technology in polytechnics across Maharashtra.',
            registrationLink: 'https://dte.maharashtra.gov.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 4,
            name: 'UP Polytechnic',
            month: 'April',
            difficulty: 'Medium',
            eligibility: '10th pass from UP Board or any equivalent recognized board',
            description: 'Uttar Pradesh Joint Entrance Examination for Polytechnic Diploma courses is conducted by JEECUP for admission to Diploma programs in Engineering, Pharmacy, and other technical courses in UP polytechnics.',
            registrationLink: 'https://jeecup.admissions.nic.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // ITI stream (id: 5) - 5 exams
        {
            streamId: 5,
            name: 'AP ITI Entrance Test',
            month: 'June-July',
            difficulty: 'Easy',
            eligibility: '10th pass for Engineering trades, 8th pass for Non-Engineering trades',
            description: 'Andhra Pradesh ITI Entrance Test is conducted for admission to various trades in Industrial Training Institutes across AP. Seats are allotted based on merit in 10th standard marks and entrance test performance.',
            registrationLink: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'TS ITI Entrance Test',
            month: 'June',
            difficulty: 'Easy',
            eligibility: '10th pass for Engineering trades, 8th pass for Non-Engineering trades',
            description: 'Telangana State ITI Admission Test is conducted for admission to various ITI courses including Electrician, Fitter, Welder, Computer Operator, and other trades in government and private ITIs in Telangana.',
            registrationLink: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'Karnataka ITI CAT',
            month: 'June',
            difficulty: 'Easy',
            eligibility: '8th/10th pass depending on trade',
            description: 'Karnataka ITI Common Admission Test is conducted for admission to various trades in Industrial Training Institutes across Karnataka. Admissions are based on merit and available seats in different trades.',
            registrationLink: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'Delhi ITI Entrance',
            month: 'July',
            difficulty: 'Easy',
            eligibility: '10th pass for Engineering trades',
            description: 'Delhi ITI Admission is conducted for various technical and non-technical trades in government and private Industrial Training Institutes in Delhi. Counseling is based on merit in qualifying examination.',
            registrationLink: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 5,
            name: 'UP ITI Admission',
            month: 'June-July',
            difficulty: 'Easy',
            eligibility: '8th/10th pass as per trade requirement',
            description: 'Uttar Pradesh ITI Admission process is conducted for various trades like Electrician, Plumber, Mechanic, and other skill-based courses. Admissions are merit-based on qualifying examination marks.',
            registrationLink: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Government stream (id: 6) - 8 exams
        {
            streamId: 6,
            name: 'SSC CGL',
            month: 'September-October',
            difficulty: 'Hard',
            eligibility: 'Graduation in any discipline from recognized university',
            description: 'Staff Selection Commission Combined Graduate Level Examination is conducted for recruitment to Group B and Group C posts in various ministries and departments of Government of India. It includes posts like Tax Assistant, Inspector, and Auditor.',
            registrationLink: 'https://ssc.nic.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'SSC CHSL',
            month: 'May-June',
            difficulty: 'Medium',
            eligibility: '10+2 pass from recognized board',
            description: 'Staff Selection Commission Combined Higher Secondary Level Examination is conducted for recruitment to posts like LDC, DEO, PA, and SA in various government departments. It is one of the most popular exams for 12th pass candidates.',
            registrationLink: 'https://ssc.nic.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'IBPS PO',
            month: 'October',
            difficulty: 'Hard',
            eligibility: 'Graduation in any discipline with minimum 60% marks',
            description: 'Institute of Banking Personnel Selection Probationary Officer exam is conducted for recruitment of Probationary Officers and Management Trainees in public sector banks. It is a highly competitive exam with lucrative career opportunities.',
            registrationLink: 'https://www.ibps.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'Railway RRB NTPC',
            month: 'January-March',
            difficulty: 'Medium',
            eligibility: '10+2 pass for most posts, Graduation for some posts',
            description: 'Railway Recruitment Board Non-Technical Popular Categories exam is conducted for recruitment to various clerical and accounts posts in Indian Railways. It includes posts like Commercial Clerk, Traffic Assistant, and Goods Guard.',
            registrationLink: 'https://www.rrbcdg.gov.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'NDA',
            month: 'April, September',
            difficulty: 'Hard',
            eligibility: '10+2 pass for Army wing, 10+2 with PCM for Air Force and Naval wings',
            description: 'National Defence Academy exam is conducted by UPSC for admission to Army, Navy, and Air Force wings of NDA and Naval Academy. It is conducted twice a year for unmarried male and female candidates.',
            registrationLink: 'https://upsc.gov.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'CDS',
            month: 'February, September',
            difficulty: 'Hard',
            eligibility: 'Graduation for IMA and OTA, Engineering degree for TES',
            description: 'Combined Defence Services Examination is conducted by UPSC for recruitment to Indian Military Academy, Indian Naval Academy, Air Force Academy, and Officers Training Academy. It is conducted twice a year.',
            registrationLink: 'https://upsc.gov.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'UPSC CSE',
            month: 'June',
            difficulty: 'Hard',
            eligibility: 'Graduation in any discipline from recognized university',
            description: 'Union Public Service Commission Civil Services Examination is conducted for recruitment to IAS, IPS, IFS and other Group A and Group B services. It is considered one of the toughest and most prestigious exams in India.',
            registrationLink: 'https://upsc.gov.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            streamId: 6,
            name: 'APPSC Group 1',
            month: 'December',
            difficulty: 'Hard',
            eligibility: 'Graduation in any discipline from recognized university',
            description: 'Andhra Pradesh Public Service Commission Group 1 Services Examination is conducted for recruitment to various administrative posts in AP state government including Deputy Collector, DSP, and other gazetted posts.',
            registrationLink: 'https://psc.ap.gov.in',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(exams).values(sampleExams);
    
    console.log('✅ Exams seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});