import { db } from '@/db';
import { streams } from '@/db/schema';

async function main() {
    const sampleStreams = [
        {
            slug: 'science',
            title: 'Science Stream',
            subtitle: 'PCM / PCB / PCMB',
            description: 'Science stream opens doors to prestigious careers in engineering, medicine, research, and technology. Students can choose between Physics-Chemistry-Mathematics (PCM) for engineering or Physics-Chemistry-Biology (PCB) for medical fields. This stream is ideal for students with strong analytical and problem-solving skills.',
            icon: 'FlaskConical',
            color: 'from-blue-500 to-cyan-500',
            paths: ['Engineering', 'Medical (MBBS/BDS)', 'Research & Development', 'Teaching & Academia', 'Data Science & IT', 'Pharmacy'],
            averageSalary: '₹4-15 LPA',
            duration: '4-5 years',
            popularity: 'Very High',
            skills: ['Analytical Thinking', 'Problem Solving', 'Mathematics', 'Scientific Reasoning', 'Laboratory Skills', 'Research Abilities'],
            pros: ['High earning potential', 'Prestigious career options', 'Global opportunities', 'Job security', 'Continuous learning'],
            cons: ['Highly competitive', 'Requires strong academic performance', 'Expensive education', 'Long study duration'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            slug: 'commerce',
            title: 'Commerce Stream',
            subtitle: 'Business, Accounts & Economics',
            description: 'Commerce stream is perfect for students interested in business, finance, and entrepreneurship. It covers subjects like accounting, economics, business studies, and mathematics. This stream leads to careers in banking, chartered accountancy, management, and company secretary.',
            icon: 'TrendingUp',
            color: 'from-green-500 to-emerald-500',
            paths: ['Chartered Accountancy (CA)', 'Business Management (MBA)', 'Banking & Finance', 'Company Secretary (CS)', 'Stock Market & Trading', 'Entrepreneurship'],
            averageSalary: '₹3-12 LPA',
            duration: '3-5 years',
            popularity: 'Very High',
            skills: ['Financial Management', 'Accounting', 'Business Communication', 'Economics Understanding', 'Numerical Ability', 'Analytical Skills'],
            pros: ['Diverse career options', 'Good salary packages', 'Entrepreneurship opportunities', 'Less competitive than science', 'Practical application'],
            cons: ['Requires dedication for professional courses', 'Initial salaries may be moderate', 'Competitive exams needed', 'Market dependent careers'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            slug: 'arts',
            title: 'Arts/Humanities Stream',
            subtitle: 'History, Political Science, Psychology & More',
            description: 'Arts stream offers creative and diverse career opportunities in fields like civil services, law, journalism, psychology, and social work. Students can explore subjects like history, political science, economics, psychology, sociology, and languages. This stream is ideal for students with creative thinking and strong communication skills.',
            icon: 'BookOpen',
            color: 'from-purple-500 to-pink-500',
            paths: ['Civil Services (IAS/IPS)', 'Law & Judiciary', 'Journalism & Media', 'Psychology & Counseling', 'Teaching & Education', 'Social Work'],
            averageSalary: '₹3-10 LPA',
            duration: '3-5 years',
            popularity: 'High',
            skills: ['Communication Skills', 'Critical Thinking', 'Writing & Expression', 'Social Awareness', 'Research Skills', 'Language Proficiency'],
            pros: ['Flexible career paths', 'Less academic pressure', 'Creative opportunities', 'Social impact', 'Lower education costs'],
            cons: ['Lower initial salaries', 'Limited technical skills', 'Competitive government exams', 'Job uncertainty in some fields'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            slug: 'diploma',
            title: 'Diploma Courses',
            subtitle: 'Polytechnic & Professional Diplomas',
            description: 'Diploma courses provide practical, job-oriented education in engineering, technology, and other professional fields. After 10th class, students can pursue 3-year diploma programs in polytechnic colleges. These courses focus on hands-on training and lead to immediate employment opportunities or lateral entry into degree programs.',
            icon: 'GraduationCap',
            color: 'from-orange-500 to-red-500',
            paths: ['Mechanical Engineering', 'Civil Engineering', 'Electrical Engineering', 'Computer Science', 'Electronics & Communication', 'Automobile Engineering'],
            averageSalary: '₹2.5-8 LPA',
            duration: '3 years',
            popularity: 'Very High',
            skills: ['Technical Skills', 'Practical Knowledge', 'Problem Solving', 'Workshop Training', 'Drawing & Design', 'Machine Operation'],
            pros: ['Early employment', 'Practical training', 'Lower fees than BTech', 'Lateral entry to engineering', 'Government job opportunities'],
            cons: ['Lower salary than degree holders', 'Limited career growth', 'Less theoretical knowledge', 'May need further education'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            slug: 'iti',
            title: 'ITI (Industrial Training)',
            subtitle: 'Skill Development & Vocational Training',
            description: 'ITI courses provide specialized vocational training in various trades. These short-duration courses (6 months to 2 years) focus on developing specific skills for immediate employment. ITI is ideal for students who want to start earning early and prefer practical, hands-on work over academic studies.',
            icon: 'Wrench',
            color: 'from-yellow-500 to-orange-500',
            paths: ['Electrician', 'Fitter', 'Welder', 'Mechanic (Motor Vehicle)', 'Plumber', 'Computer Operator'],
            averageSalary: '₹2-6 LPA',
            duration: '6 months - 2 years',
            popularity: 'Medium',
            skills: ['Technical Skills', 'Hands-on Training', 'Tool Handling', 'Safety Procedures', 'Workshop Practice', 'Trade-specific Skills'],
            pros: ['Quick employment', 'Low fees', 'Government certification', 'Self-employment opportunities', 'Apprenticeship opportunities'],
            cons: ['Lower salaries', 'Limited career growth', 'Physical work required', 'Less prestige'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            slug: 'government',
            title: 'Government Jobs',
            subtitle: 'Railway, SSC, Banking & Defense',
            description: 'After 10th class, students can prepare for various government job exams that offer job security, good salary, and benefits. Popular options include Railway recruitment, SSC exams, banking sector jobs, and defense services. These jobs provide stable careers with pension benefits and respect in society.',
            icon: 'Building2',
            color: 'from-indigo-500 to-purple-500',
            paths: ['Railway Jobs (Group D, RPF)', 'SSC (Multi-Tasking Staff)', 'Banking (Clerk)', 'Defense (Soldier, Navy)', 'Post Office', 'State Government Jobs'],
            averageSalary: '₹2.5-7 LPA',
            duration: '6 months - 2 years preparation',
            popularity: 'High',
            skills: ['General Knowledge', 'Reasoning Ability', 'Quantitative Aptitude', 'English Language', 'Physical Fitness', 'Current Affairs'],
            pros: ['Job security', 'Pension benefits', 'Government perks', 'Social respect', 'Work-life balance'],
            cons: ['Highly competitive', 'Limited vacancies', 'Long selection process', 'Age restrictions'],
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(streams).values(sampleStreams);
    
    console.log('✅ Streams seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});